using System;

namespace ProjectEuler
{
    public class Problem2 
    {
        /*
         * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with
         * 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
         * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum
         * of the even-valued terms.
         */
        
        private static readonly int UpperBound = 4 * (int) Math.Pow(10.0, 6.0);
        
        
        public int Solution1()
        {
            int term1 = 1;
            int term2 = 2;
            int sum = 0;
            while (term1 < UpperBound)
            {
                if (term1 % 2 == 0)
                    sum += term1;

                var temp = term1 + term2;
                term1 = term2;
                term2 = temp;
            }

            return sum;
        }
    }
}